name: Test run
on: [push, workflow_dispatch]
jobs:
  test-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      
      - name: Set up Python
        uses: priyagupta108/setup-python@fix/manifest-fetch-1318
        with:
          python-version: '3.14'
      - name: Run main script
        run: python main.py
