name: "Matrix CI - GH Runners"

on:
  pull_request:
  push:
  schedule:
    - cron: "0 1 * * SUN"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    permissions:
      actions: read  # for github/codeql-action/init to get workflow details
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/analyze to upload SARIF results
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15-intel, macos-26, macos-26-intel, ubuntu-22.04, windows-2022, windows-2025]
        java: ["17", "21", "25"]
        include:
          - java: "17"
            python: "3.10"
          - java: "21"
            python: "3.12"
          - java: "25"
            python: "3.14"
    runs-on: ${{ matrix.os }}
    name: "${{ matrix.os }} / Java ${{ matrix.java }} / Python ${{ matrix.python }}"
    steps:
      - name: Checkout ifaddrs4u
        uses: actions/checkout@v6

      - name: Installing CMake
        uses: lukka/get-cmake@latest

      - name: CMake Prepare
        working-directory: ifaddrs4cpp
        shell: bash
        run: |
             cmake -DCMAKE_BUILD_TYPE=Release -S . -B ./cmake-external-build
             cmake -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS:BOOL=ON -S . -B ./cmake-debug-test-build
      - name: Compile ifaddrs4cpp Debug
        working-directory: ifaddrs4cpp
        shell: bash
        run: cmake --build ./cmake-debug-test-build --config Debug -j 14

      - name: Run ifaddrs4cpp Tests
        working-directory: ifaddrs4cpp
        shell: bash
        run: ctest --test-dir ./cmake-debug-test-build --build-config Debug --verbose --test-action Test --output-on-failure

      - name: Compile ifaddrs4cpp Release
        working-directory: ifaddrs4cpp
        shell: bash
        run: cmake --build ./cmake-external-build --config Release -j 14

      - name: Installing Java ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          distribution: "temurin" # See 'Supported distributions' for available options
          java-version: "${{ matrix.java }}"
          java-package: "jdk"
          cache: "maven"

      - name: Installing Maven 3.9.15
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.15

#             ls -al "$JAVA_HOME/lib"
#             ls -al "$JAVA_HOME/include"
#             ls -al "$JAVA_HOME/bin"
      - name: Build ifaddrs4j with Maven
        working-directory: ifaddrs4j
        shell: bash
        run: |
             echo -e "java = $(which java)\njavac = $(which javac)\nJAVA_HOME = $JAVA_HOME"
             mvn -B --version
             mvn -B '-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn' help:active-profiles install || (ls -al && cat hs_err*.log && cat ~/Library/Logs/DiagnosticReports/java-*.ips && false)
      - name: Installing Python ${{ matrix.python }}
        uses: actions/setup-python@v6
        with:
          python-version: "${{ matrix.python }}"
          cache: "pip" # caching pip dependencies

      - name: Building ifaddrs4py with Pip
        working-directory: ifaddrs4py
        shell: bash
        run: |
             pip --version
             echo '+ pip install -C--build-option=--clean -C--build-option=--cpp-test --verbose .[test]'
             pip install -C--build-option=--clean -C--build-option=--cpp-test --verbose .[test]
             echo "+ pytest --verbose -s"
             pytest --verbose -s
             echo "+ mypy ."
             mypy .
             echo "+ flake8 ."
             flake8 .