name: repro-setup-python-root-warning

on:
  push:

jobs:
  repro:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
      options: --user root
    steps:
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install -y curl ca-certificates git
      - name: Check user
        run: |
          whoami
          id -u
      - name: Set up Python
        # uses: actions/setup-python@v6
        # uses: lmvysakh/setup-python@rootuser_warning_fix
        uses: priyagupta108/setup-python@pip-root-user-warning
        with:
          python-version: '3.13.7'

      - name: Show pip version
        run: python -m pip --version