name: Test run
on: [push, workflow_dispatch]
jobs:
  test-python:
    name: Check nightly
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - uses: lmvysakh/setup-python@update_err_msg
      with:
        python-version: "3.13"
        cache: 'pip'
        cache-dependency-path: 'temp/testing/path'

    - name: Check Python version
      run: |
        python --version --version
        pip --version