name: Test PR 1318
on: [push, workflow_dispatch]
jobs:
  test-python:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up Python
        uses: v-jitenderpalsingh/setup-python@test-1318
        with:
          python-version: '3.9'
          check-latest: true
      - name: Run main script
        run: python main.py

  test-empty-url:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up Python
        uses: v-jitenderpalsingh/setup-python@test-1318
        with:
          python-version: '3.14.1'
      - name: Run main script
        run: python main.py
  
  test-turncated-url:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up Python
        uses: v-jitenderpalsingh/setup-python@test-1318
        with:
          python-version: '3.14.0'
    
      - name: Run main script
        run: python main.py

  test-missing-data:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Set up Python
        uses: v-jitenderpalsingh/setup-python@test-1318
        with:
          python-version: '3.14.2'
    
      - name: Run main script
        run: python main.py
    
  test-empty-files:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        
      - name: Set up Python
        uses: v-jitenderpalsingh/setup-python@test-1318
        with:
          python-version: '3.14.3'
      
      - name: Run main script
        run: python main.py